# Generated by Django 2.2.6 on 2020-07-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20200720_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_login_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='设备最上线时间'),
        ),
    ]
