# Generated by Django 2.2.6 on 2020-07-22 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
        ('device', '0008_auto_20200721_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='grid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.Grid'),
        ),
    ]
